before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/reposaur/reposaur/internal/build.Version={{.Version}}

archives:
  - replacements:
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: reposaur
    name: reposaur
  prerelease: auto
