before:
  hooks:
    - go mod tidy
    - go vet ./...
    - ./scripts/completions.sh

builds:
  - id: rsr
    binary: rsr
    main: ./cmd/rsr/rsr.go
    ldflags:
      - -s -w -X github.com/reposaur/reposaur/internal/build.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: reposaur
    binary: reposaur
    main: ./cmd/rsr/rsr.go
    ldflags:
      - -s -w -X github.com/reposaur/reposaur/internal/build.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^build:"
  groups:
    - title: 'New Features and updates'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other work
      order: 999

release:
  github:
    owner: reposaur
    name: reposaur
  prerelease: auto

brews:
  - tap:
      owner: reposaur
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    commit_msg_template: "chore: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://reposaur.com"
    description: "The open source compliance tool for development platforms."
    license: "MIT"
    test: |
      system "#{bin}/rsr --version"
    install: |-
      bin.install "rsr"
      bash_completion.install "completions/rsr.bash" => "rsr"
      zsh_completion.install "completions/rsr.zsh" => "_rsr"
      fish_completion.install "completions/rsr.fish"

nfpms:
  - vendor: Reposaur
    homepage: https://reposaur.com/
    maintainer: João Cerqueira <oss@cerqueira.io>
    description: |-
      The open source compliance tool for development platforms.
    license: MIT
    contents:
      - src: ./completions/rsr.bash
        dst: /usr/share/bash-completion/completions/rsr
        file_info:
          mode: 0644
      - src: ./completions/rsr.fish
        dst: /usr/share/fish/completions/rsr.fish
        file_info:
          mode: 0644
      - src: ./completions/rsr.zsh
        dst:  /usr/share/zsh/vendor-completions/_rsr
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/rsr/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    section: utils
    priority: extra
