before:
  hooks:
    - go mod tidy
    - go vet ./...
builds:
  - id: rsr
    binary: rsr
    main: ./cmd/rsr/rsr.go
    ldflags:
      - -s -w -X github.com/reposaur/reposaur/internal/build.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: reposaur
    binary: reposaur
    main: ./cmd/rsr/rsr.go
    ldflags:
      - -s -w -X github.com/reposaur/reposaur/internal/build.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: reposaur
    name: reposaur
  prerelease: auto
brews:
  - tap:
      owner: reposaur
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    commit_msg_template: "chore: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://reposaur.com"
    description: "The open source compliance tool for development platforms."
    license: "MIT"